In [110]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

In [111]:

import os, types
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0


cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='bmTZ1tDihoDNN3IgTrgFVwo7l1Lgc9kntdKX4gUvHR1x',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'vehicleperformanceanalyzer-donotdelete-pr-vbny2haofpbejk'
object_key = 'Car_Performance.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']

if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino

In [112]:
dataset.isnull().any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

There are no null characters in the columns but there is a special character '?' in the 'horsepower' column. So we we replaced '?' with nan and replaced nan values with mean of the column.

In [113]:
dataset['horsepower']=dataset['horsepower'].replace('?',np.nan)


In [114]:
dataset['horsepower'].isnull().sum()

0

In [115]:
dataset['horsepower']=dataset['horsepower'].astype('float64')

In [116]:
dataset['horsepower'].fillna((dataset['horsepower'].mean()),inplace=True)

In [117]:
dataset.isnull().any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

In [118]:
dataset.info() #Pandas dataframe.info() function is used to get a quick overview of the dataset.


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB


In [119]:
dataset.describe() #Pandas describe() is used to view some basic statistical details of a data frame or a series of numeric values.

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  398.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.165829  2970.424623   
std      7.815984    1.701004    104.269838   38.298676   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   92.000000  2803.500000   
75%     29.000000    8.000000    262.000000  125.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model year      origin  
count    398.000000  398.000000  398.000000  
mean      15.568090   76.010050    1.572864  
std        2.757689    3.697627    0.802055  
min        8.000000   70.000000    1.000000  
25%       13.825000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.175000   79.000000    2.000000  
max       24.800000   82.000000    3.000000

There is no use with car name attribute so drop it

In [120]:
dataset=dataset.drop('car name',axis=1) #dropping the unwanted column.

In [121]:
corr_table=dataset.corr()#Pandas dataframe.corr() is used to find the pairwise correlation of all columns in the dataframe. 
corr_table

mpg  cylinders  displacement  horsepower    weight  \
mpg           1.000000  -0.775396     -0.804203   -0.777501 -0.831741   
cylinders    -0.775396   1.000000      0.950721    0.842437  0.896017   
displacement -0.804203   0.950721      1.000000    0.897082  0.932824   
horsepower   -0.777501   0.842437      0.897082    1.000000  0.863990   
weight       -0.831741   0.896017      0.932824    0.863990  1.000000   
acceleration  0.420289  -0.505419     -0.543684   -0.686436 -0.417457   
model year    0.579267  -0.348746     -0.370164   -0.417081 -0.306564   
origin        0.563450  -0.562543     -0.609409   -0.452386 -0.581024   

              acceleration  model year    origin  
mpg               0.420289    0.579267  0.563450  
cylinders        -0.505419   -0.348746 -0.562543  
displacement     -0.543684   -0.370164 -0.609409  
horsepower       -0.686436   -0.417081 -0.452386  
weight           -0.417457   -0.306564 -0.581024  
acceleration      1.000000    0.288137  0.205873  
model year        0.288137    1.000000  0.180662  
origin            0.205873    0.180662  1.000000

# Seperating into Dependent and Independent variables

<b>Independent variables</b>

In [122]:
x=dataset[['cylinders','displacement','horsepower','weight','acceleration','model year','origin']].values
x

array([[  8. , 307. , 130. , ...,  12. ,  70. ,   1. ],
       [  8. , 350. , 165. , ...,  11.5,  70. ,   1. ],
       [  8. , 318. , 150. , ...,  11. ,  70. ,   1. ],
       ...,
       [  4. , 135. ,  84. , ...,  11.6,  82. ,   1. ],
       [  4. , 120. ,  79. , ...,  18.6,  82. ,   1. ],
       [  4. , 119. ,  82. , ...,  19.4,  82. ,   1. ]])

<b>Dependent variables</b>

In [123]:
y=dataset.iloc[:,0:1].values
y

array([[18. ],
       [15. ],
       [18. ],
       [16. ],
       [17. ],
       [15. ],
       [14. ],
       [14. ],
       [14. ],
       [15. ],
       [15. ],
       [14. ],
       [15. ],
       [14. ],
       [24. ],
       [22. ],
       [18. ],
       [21. ],
       [27. ],
       [26. ],
       [25. ],
       [24. ],
       [25. ],
       [26. ],
       [21. ],
       [10. ],
       [10. ],
       [11. ],
       [ 9. ],
       [27. ],
       [28. ],
       [25. ],
       [25. ],
       [19. ],
       [16. ],
       [17. ],
       [19. ],
       [18. ],
       [14. ],
       [14. ],
       [14. ],
       [14. ],
       [12. ],
       [13. ],
       [13. ],
       [18. ],
       [22. ],
       [19. ],
       [18. ],
       [23. ],
       [28. ],
       [30. ],
       [30. ],
       [31. ],
       [35. ],
       [27. ],
       [26. ],
       [24. ],
       [25. ],
       [23. ],
       [20. ],
       [21. ],
       [13. ],
       [14. ],
       [15. ],
       [14. ],
       [17

# Splitting into train and test data.

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)

# Normalisation

In [126]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()

x_train = sd.fit_transform(x_train)
x_test = sd.fit_transform(x_test)
y_train = sd.fit_transform(y_train)
y_test = sd.fit_transform(y_test)

x_train


array([[ 1.46858608,  2.48230464,  2.97979869, ..., -2.37109405,
        -1.61295698, -0.71873488],
       [ 1.46858608,  1.48729292,  1.55782064, ..., -1.46292048,
        -1.61295698, -0.71873488],
       [-0.86550411, -0.70364636, -0.63978179, ..., -0.19147749,
         0.82235108, -0.71873488],
       ...,
       [-0.86550411, -1.21071964, -1.44126033, ...,  1.44323493,
        -0.80118763,  0.53032865],
       [ 0.30154098,  0.53055088, -0.12269887, ..., -0.19147749,
        -1.3423672 , -0.71873488],
       [-0.86550411, -1.00023639, -0.87246911, ...,  0.35342665,
        -0.26000806,  0.53032865]])

In [127]:
#TRAINING THE MODEL

from sklearn.ensemble import RandomForestRegressor

r = RandomForestRegressor(n_estimators = 100, random_state = 0) 
r.fit(x_train, y_train.ravel())
y_pred = r.predict(x_test)

In [128]:
#SCORING THE MODEL

import sklearn.metrics as mt
accuracy = mt.r2_score(y_test, y_pred)
accuracy

0.9231246807234993

In [129]:
!pip install ibm_watson_machine_learning

In [130]:
from ibm_watson_machine_learning import APIClient
wml_cred = {
    'url': 'https://us-south.ml.cloud.ibm.com',
    'apikey': 'hS4CGi9PpGEJH4LVNkKH9oys9lA0dughL6i0Sxm2bmh6'
}
client = APIClient(wml_cred)

In [131]:
def get_space(client, space_name):
    space = client.spaces.get_details()
    return(next(item for item in space['resources'] if item['entity']['name'] == space_name)['metadata']['id'])

In [132]:
space_uid = get_space(client, 'IBM project')
client.set.default_space(space_uid)
space_uid

'ed52c942-4882-486a-86a6-8e492074cae8'

In [133]:
software_spec_uid = client.software_specifications.get_uid_by_name("runtime-22.1-py3.9")
software_spec_uid

'12b83a17-24d8-5082-900f-0ab31fbfd3cb'

In [134]:
meta_props = {
    client.repository.ModelMetaNames.NAME: "ML_model",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid,
    client.repository.ModelMetaNames.TYPE: "scikit-learn_1.0"}

stored_model = client.repository.store_model(model=r, meta_props=meta_props)

model_id = client.repository.get_model_id(stored_model)
print(model_id)

99addf54-d3fe-42f4-adc8-460cf7fc2dd6
